name: build-and-push-to-dh
on:
   schedule:
     # * is a special character in YAML so you have to quote this string
     - cron:  '30 21 * * *'
jobs:
  scheduled-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DH_USERNAME }}
            password: ${{ secrets.DH_TOKEN }}
      - name: config git
        run: git config --global user.email "workflow@github.com" && git config --global user.name "Automated workflow"
      - name: build-and-push
        run: ./build-all.sh
